/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as DatasetsIdRouteImport } from './routes/datasets.$id'
import { Route as DatasetsNewRouteImport } from './routes/datasets.new'
import { Route as ImportsIndexRouteImport } from './routes/imports.index'
import { Route as ImportsJobIdRouteImport } from './routes/imports.$jobId'
import { Route as ImportsNewRouteImport } from './routes/imports.new'
import { Route as PublishesIndexRouteImport } from './routes/publishes.index'
import { Route as PublishesJobIdRouteImport } from './routes/publishes.$jobId'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsIdRouteImport } from './routes/runs.$id'
import { Route as RunsNewRouteImport } from './routes/runs.new'
import { Route as SettingsLangfuseRouteImport } from './routes/settings.langfuse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsIdRoute = DatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsNewRoute = DatasetsNewRouteImport.update({
  id: '/datasets/new',
  path: '/datasets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsIndexRoute = ImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsJobIdRoute = ImportsJobIdRouteImport.update({
  id: '/imports/$jobId',
  path: '/imports/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsNewRoute = ImportsNewRouteImport.update({
  id: '/imports/new',
  path: '/imports/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishesIndexRoute = PublishesIndexRouteImport.update({
  id: '/publishes/',
  path: '/publishes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishesJobIdRoute = PublishesJobIdRouteImport.update({
  id: '/publishes/$jobId',
  path: '/publishes/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsNewRoute = RunsNewRouteImport.update({
  id: '/runs/new',
  path: '/runs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLangfuseRoute = SettingsLangfuseRouteImport.update({
  id: '/settings/langfuse',
  path: '/settings/langfuse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/calculators': typeof CalculatorsRoute
  '/reports': typeof ReportsRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/new': typeof DatasetsNewRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/publishes/$jobId': typeof PublishesJobIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/langfuse': typeof SettingsLangfuseRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/publishes/': typeof PublishesIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/calculators': typeof CalculatorsRoute
  '/reports': typeof ReportsRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/new': typeof DatasetsNewRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/publishes/$jobId': typeof PublishesJobIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/langfuse': typeof SettingsLangfuseRoute
  '/datasets': typeof DatasetsIndexRoute
  '/imports': typeof ImportsIndexRoute
  '/publishes': typeof PublishesIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/calculators': typeof CalculatorsRoute
  '/reports': typeof ReportsRoute
  '/datasets/$id': typeof DatasetsIdRoute
  '/datasets/new': typeof DatasetsNewRoute
  '/imports/$jobId': typeof ImportsJobIdRoute
  '/imports/new': typeof ImportsNewRoute
  '/publishes/$jobId': typeof PublishesJobIdRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/new': typeof RunsNewRoute
  '/settings/langfuse': typeof SettingsLangfuseRoute
  '/datasets/': typeof DatasetsIndexRoute
  '/imports/': typeof ImportsIndexRoute
  '/publishes/': typeof PublishesIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/calculators'
    | '/reports'
    | '/datasets/$id'
    | '/datasets/new'
    | '/imports/$jobId'
    | '/imports/new'
    | '/publishes/$jobId'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/langfuse'
    | '/datasets/'
    | '/imports/'
    | '/publishes/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/calculators'
    | '/reports'
    | '/datasets/$id'
    | '/datasets/new'
    | '/imports/$jobId'
    | '/imports/new'
    | '/publishes/$jobId'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/langfuse'
    | '/datasets'
    | '/imports'
    | '/publishes'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/calculators'
    | '/reports'
    | '/datasets/$id'
    | '/datasets/new'
    | '/imports/$jobId'
    | '/imports/new'
    | '/publishes/$jobId'
    | '/runs/$id'
    | '/runs/new'
    | '/settings/langfuse'
    | '/datasets/'
    | '/imports/'
    | '/publishes/'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ReportsRoute: typeof ReportsRoute
  DatasetsIdRoute: typeof DatasetsIdRoute
  DatasetsNewRoute: typeof DatasetsNewRoute
  ImportsJobIdRoute: typeof ImportsJobIdRoute
  ImportsNewRoute: typeof ImportsNewRoute
  PublishesJobIdRoute: typeof PublishesJobIdRoute
  RunsIdRoute: typeof RunsIdRoute
  RunsNewRoute: typeof RunsNewRoute
  SettingsLangfuseRoute: typeof SettingsLangfuseRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
  ImportsIndexRoute: typeof ImportsIndexRoute
  PublishesIndexRoute: typeof PublishesIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/datasets'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/$id': {
      id: '/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/datasets/$id'
      preLoaderRoute: typeof DatasetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets/new': {
      id: '/datasets/new'
      path: '/datasets/new'
      fullPath: '/datasets/new'
      preLoaderRoute: typeof DatasetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/': {
      id: '/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof ImportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/$jobId': {
      id: '/imports/$jobId'
      path: '/imports/$jobId'
      fullPath: '/imports/$jobId'
      preLoaderRoute: typeof ImportsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports/new': {
      id: '/imports/new'
      path: '/imports/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof ImportsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishes/': {
      id: '/publishes/'
      path: '/publishes'
      fullPath: '/publishes/'
      preLoaderRoute: typeof PublishesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishes/$jobId': {
      id: '/publishes/$jobId'
      path: '/publishes/$jobId'
      fullPath: '/publishes/$jobId'
      preLoaderRoute: typeof PublishesJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/new': {
      id: '/runs/new'
      path: '/runs/new'
      fullPath: '/runs/new'
      preLoaderRoute: typeof RunsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/langfuse': {
      id: '/settings/langfuse'
      path: '/settings/langfuse'
      fullPath: '/settings/langfuse'
      preLoaderRoute: typeof SettingsLangfuseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CalculatorsRoute: CalculatorsRoute,
  ReportsRoute: ReportsRoute,
  DatasetsIdRoute: DatasetsIdRoute,
  DatasetsNewRoute: DatasetsNewRoute,
  ImportsJobIdRoute: ImportsJobIdRoute,
  ImportsNewRoute: ImportsNewRoute,
  PublishesJobIdRoute: PublishesJobIdRoute,
  RunsIdRoute: RunsIdRoute,
  RunsNewRoute: RunsNewRoute,
  SettingsLangfuseRoute: SettingsLangfuseRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
  ImportsIndexRoute: ImportsIndexRoute,
  PublishesIndexRoute: PublishesIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
