/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdDatasetsRouteImport } from './routes/projects.$projectId.datasets'
import { Route as ProjectsProjectIdTestSetsRouteImport } from './routes/projects.$projectId.test-sets'
import { Route as ProjectsProjectIdDatasetsCollectionIdRouteImport } from './routes/projects.$projectId.datasets.$collectionId'
import { Route as ProjectsProjectIdTestSetsTestSetIdRouteImport } from './routes/projects.$projectId.test-sets.$testSetId'
import { Route as ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRouteImport } from './routes/projects.$projectId.datasets.$collectionId.files.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdDatasetsRoute =
  ProjectsProjectIdDatasetsRouteImport.update({
    id: '/projects/$projectId/datasets',
    path: '/projects/$projectId/datasets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdTestSetsRoute =
  ProjectsProjectIdTestSetsRouteImport.update({
    id: '/projects/$projectId/test-sets',
    path: '/projects/$projectId/test-sets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdDatasetsCollectionIdRoute =
  ProjectsProjectIdDatasetsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => ProjectsProjectIdDatasetsRoute,
  } as any)
const ProjectsProjectIdTestSetsTestSetIdRoute =
  ProjectsProjectIdTestSetsTestSetIdRouteImport.update({
    id: '/$testSetId',
    path: '/$testSetId',
    getParentRoute: () => ProjectsProjectIdTestSetsRoute,
  } as any)
const ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute =
  ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRouteImport.update({
    id: '/files/$assetId',
    path: '/files/$assetId',
    getParentRoute: () => ProjectsProjectIdDatasetsCollectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/datasets': typeof ProjectsProjectIdDatasetsRouteWithChildren
  '/projects/$projectId/test-sets': typeof ProjectsProjectIdTestSetsRouteWithChildren
  '/projects/$projectId/datasets/$collectionId': typeof ProjectsProjectIdDatasetsCollectionIdRouteWithChildren
  '/projects/$projectId/test-sets/$testSetId': typeof ProjectsProjectIdTestSetsTestSetIdRoute
  '/projects/$projectId/datasets/$collectionId/files/$assetId': typeof ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/datasets': typeof ProjectsProjectIdDatasetsRouteWithChildren
  '/projects/$projectId/test-sets': typeof ProjectsProjectIdTestSetsRouteWithChildren
  '/projects/$projectId/datasets/$collectionId': typeof ProjectsProjectIdDatasetsCollectionIdRouteWithChildren
  '/projects/$projectId/test-sets/$testSetId': typeof ProjectsProjectIdTestSetsTestSetIdRoute
  '/projects/$projectId/datasets/$collectionId/files/$assetId': typeof ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/datasets': typeof ProjectsProjectIdDatasetsRouteWithChildren
  '/projects/$projectId/test-sets': typeof ProjectsProjectIdTestSetsRouteWithChildren
  '/projects/$projectId/datasets/$collectionId': typeof ProjectsProjectIdDatasetsCollectionIdRouteWithChildren
  '/projects/$projectId/test-sets/$testSetId': typeof ProjectsProjectIdTestSetsTestSetIdRoute
  '/projects/$projectId/datasets/$collectionId/files/$assetId': typeof ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/'
    | '/projects/$projectId/datasets'
    | '/projects/$projectId/test-sets'
    | '/projects/$projectId/datasets/$collectionId'
    | '/projects/$projectId/test-sets/$testSetId'
    | '/projects/$projectId/datasets/$collectionId/files/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId/datasets'
    | '/projects/$projectId/test-sets'
    | '/projects/$projectId/datasets/$collectionId'
    | '/projects/$projectId/test-sets/$testSetId'
    | '/projects/$projectId/datasets/$collectionId/files/$assetId'
  id:
    | '__root__'
    | '/'
    | '/projects/'
    | '/projects/$projectId/datasets'
    | '/projects/$projectId/test-sets'
    | '/projects/$projectId/datasets/$collectionId'
    | '/projects/$projectId/test-sets/$testSetId'
    | '/projects/$projectId/datasets/$collectionId/files/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdDatasetsRoute: typeof ProjectsProjectIdDatasetsRouteWithChildren
  ProjectsProjectIdTestSetsRoute: typeof ProjectsProjectIdTestSetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/datasets': {
      id: '/projects/$projectId/datasets'
      path: '/projects/$projectId/datasets'
      fullPath: '/projects/$projectId/datasets'
      preLoaderRoute: typeof ProjectsProjectIdDatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/test-sets': {
      id: '/projects/$projectId/test-sets'
      path: '/projects/$projectId/test-sets'
      fullPath: '/projects/$projectId/test-sets'
      preLoaderRoute: typeof ProjectsProjectIdTestSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/datasets/$collectionId': {
      id: '/projects/$projectId/datasets/$collectionId'
      path: '/$collectionId'
      fullPath: '/projects/$projectId/datasets/$collectionId'
      preLoaderRoute: typeof ProjectsProjectIdDatasetsCollectionIdRouteImport
      parentRoute: typeof ProjectsProjectIdDatasetsRoute
    }
    '/projects/$projectId/test-sets/$testSetId': {
      id: '/projects/$projectId/test-sets/$testSetId'
      path: '/$testSetId'
      fullPath: '/projects/$projectId/test-sets/$testSetId'
      preLoaderRoute: typeof ProjectsProjectIdTestSetsTestSetIdRouteImport
      parentRoute: typeof ProjectsProjectIdTestSetsRoute
    }
    '/projects/$projectId/datasets/$collectionId/files/$assetId': {
      id: '/projects/$projectId/datasets/$collectionId/files/$assetId'
      path: '/files/$assetId'
      fullPath: '/projects/$projectId/datasets/$collectionId/files/$assetId'
      preLoaderRoute: typeof ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRouteImport
      parentRoute: typeof ProjectsProjectIdDatasetsCollectionIdRoute
    }
  }
}

interface ProjectsProjectIdDatasetsCollectionIdRouteChildren {
  ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute: typeof ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute
}

const ProjectsProjectIdDatasetsCollectionIdRouteChildren: ProjectsProjectIdDatasetsCollectionIdRouteChildren =
  {
    ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute:
      ProjectsProjectIdDatasetsCollectionIdFilesAssetIdRoute,
  }

const ProjectsProjectIdDatasetsCollectionIdRouteWithChildren =
  ProjectsProjectIdDatasetsCollectionIdRoute._addFileChildren(
    ProjectsProjectIdDatasetsCollectionIdRouteChildren,
  )

interface ProjectsProjectIdDatasetsRouteChildren {
  ProjectsProjectIdDatasetsCollectionIdRoute: typeof ProjectsProjectIdDatasetsCollectionIdRouteWithChildren
}

const ProjectsProjectIdDatasetsRouteChildren: ProjectsProjectIdDatasetsRouteChildren =
  {
    ProjectsProjectIdDatasetsCollectionIdRoute:
      ProjectsProjectIdDatasetsCollectionIdRouteWithChildren,
  }

const ProjectsProjectIdDatasetsRouteWithChildren =
  ProjectsProjectIdDatasetsRoute._addFileChildren(
    ProjectsProjectIdDatasetsRouteChildren,
  )

interface ProjectsProjectIdTestSetsRouteChildren {
  ProjectsProjectIdTestSetsTestSetIdRoute: typeof ProjectsProjectIdTestSetsTestSetIdRoute
}

const ProjectsProjectIdTestSetsRouteChildren: ProjectsProjectIdTestSetsRouteChildren =
  {
    ProjectsProjectIdTestSetsTestSetIdRoute:
      ProjectsProjectIdTestSetsTestSetIdRoute,
  }

const ProjectsProjectIdTestSetsRouteWithChildren =
  ProjectsProjectIdTestSetsRoute._addFileChildren(
    ProjectsProjectIdTestSetsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdDatasetsRoute: ProjectsProjectIdDatasetsRouteWithChildren,
  ProjectsProjectIdTestSetsRoute: ProjectsProjectIdTestSetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
