/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './workflow-routes/__root'
import { Route as IndexRouteImport } from './workflow-routes/index'
import { Route as MaterialsRouteImport } from './workflow-routes/materials'
import { Route as TestSetsRouteImport } from './workflow-routes/test-sets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSetsRoute = TestSetsRouteImport.update({
  id: '/test-sets',
  path: '/test-sets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRoute
  '/test-sets': typeof TestSetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRoute
  '/test-sets': typeof TestSetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/materials': typeof MaterialsRoute
  '/test-sets': typeof TestSetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/materials' | '/test-sets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/materials' | '/test-sets'
  id: '__root__' | '/' | '/materials' | '/test-sets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaterialsRoute: typeof MaterialsRoute
  TestSetsRoute: typeof TestSetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-sets': {
      id: '/test-sets'
      path: '/test-sets'
      fullPath: '/test-sets'
      preLoaderRoute: typeof TestSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaterialsRoute: MaterialsRoute,
  TestSetsRoute: TestSetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
